[package]
name = "astrealrblx/toned"
description = "An extension module to Fusion with a focus on separation of functionality & design through style sheets"
authors = ["AstrealDev"]
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]

[dev-dependencies]
# Fusion = "elttob/fusion@0.2.0"